# tasks file for makkus.install-pkg-mgrs

# this doesn't work, bug in ansible, for now installing roles manually one by one
# - name: ensure all package managers are installed
#   include_role:
#     name: "{{ item }}"
#   with_items:
#     - "{{ dotfiles_repos | pkg_mgr_filter('install-') }}"

- name: install homebrew
  include_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_cask_apps: []
  when: '("homebrew" in pkg_mgrs or default_pkg_mgr == "auto") and ansible_os_family == "Darwin"'

- name: install nix
  include_role:
    name: makkus.install-nix
  when: '"nix" in pkg_mgrs'

- name: install conda
  include_role:
    name: makkus.install-conda
  when: '"conda" in pkg_mgrs'
