# tasks file for makkus.install-pkg-mgrs

# this doesn't work, bug in ansible, for now installing roles manually one by one
# - name: ensure all package managers are installed
#   include_role:
#     name: "{{ item }}"
#   with_items:
#     - "{{ dotfiles_repos | pkg_mgr_filter('install-') }}"

- name: "[check required executables]"
  required_executable_facts:
    executables_to_check: "{{ pkg_mgrs | pkg_mgr_executable_filter }}"

- name: checking for Mac OS X
  include_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_cask_apps: []
  static: no
  when: "ansible_os_family == 'Darwin' and 'brew' in executables_missing"

- name: checking whether to install nix
  include_role:
    name: makkus.install-nix
  static: no
  when: "'nix-env' in executables_missing"

- name: checking whether to install conda
  include_role:
    name: makkus.install-conda
  static: no
  when: "'conda' in executables_missing"

- name: install git
  install:
    packages:
      - git
    pkg_mgr: "{{ pkg_mgr | default('auto') }}"
  when: "'git' in executables_missing"

- name: checking whether to install Vagrant
  include_role:
    name: makkus.install-vagrant
  static: no
  when: "'vagrant' in executables_missing"

