# tasks file for makkus.install-pkg-mgrs

# this doesn't work, bug in ansible, for now installing roles manually one by one
# - name: ensure all package managers are installed
#   include_role:
#     name: "{{ item }}"
#   with_items:
#     - "{{ dotfiles_repos | pkg_mgr_filter('install-') }}"

- name: check required executables
  required_executable_facts:
    executables_to_check: "{{ pkg_mgrs | pkg_mgr_executable_filter }}"

- name: install homebrew
  include_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_cask_apps: []
  when: "'brew' in executables_missing and ansible_os_family == 'Darwin' and ('homebrew' in pkg_mgrs or default_pkg_mgr == 'auto')"

- name: install nix
  include_role:
    name: makkus.install-nix
  when: "'nix-env' in executables_missing and ('nix' in pkg_mgrs or default_pkg_mgr == 'nix')"

- name: install conda
  include_role:
    name: makkus.install-conda
  when: "'conda' in executables_missing and ('conda' in pkg_mgrs or default_pkg_mgr == 'conda')"

- name: install git
  install:
    name: git
    pkg_mgr: "{{ pkg_mgr | default('auto') }}"
  when: "'git' in executables_missing"
